# SPDX-License-Identifier: GPL-2.0

# required for overlay support
DTC_FLAGS += -@

dtb-y += maaxboard-mipi.dtb
dtb-y += maaxboard-as0260.dtb
dtb-y += maaxboard-dual-display.dtb
dtb-y += maaxboard-ext-gpio.dtb
dtb-y += maaxboard-ext-i2c.dtb
dtb-y += maaxboard-ext-pwm.dtb
dtb-y += maaxboard-ext-sai2.dtb
dtb-y += maaxboard-ext-spi.dtb
dtb-y += maaxboard-ext-uart2.dtb
dtb-y += maaxboard-ext-wm8960.dtb
dtb-y += maaxboard-hdmi.dtb
dtb-y += maaxboard-ov5640.dtb
dtb-y += maaxboard-usb0-device.dtb
dtb-y += maaxboard-imx219.dtb


dtb-y += maaxboard-nano-mipi.dtb
dtb-y += maaxboard-nano-audio.dtb
dtb-y += maaxboard-nano-mic.dtb
dtb-y += maaxboard-nano-ov5640.dtb
dtb-y += maaxboard-nano-ext-gpio.dtb
dtb-y += maaxboard-nano-ext-i2c.dtb
dtb-y += maaxboard-nano-ext-pwm.dtb
dtb-y += maaxboard-nano-ext-spi.dtb
dtb-y += maaxboard-nano-ext-uart4.dtb
dtb-y += maaxboard-nano-ext-sai3.dtb
